spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/jpashop_db;
    #    MVCC는 뭐야. 넣으면 좋기는 하다고 함
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    #      application 실행 시점에 내가 가지고 있는 것 다 지우고 처음으로 다시 생성
    properties:
      hibernate:
        show_sql: true
        #        show_sql은 sout을 이요해서 찍는 것
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    hibernate가 생성하는 모든 sql이 다 보인다.
    org.hibernate.type: trace